
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 9.2
 PARAMETER PROC_INSTANCE = microblaze_riscv_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_riscv
 PARAMETER DRIVER_VER = 1.1
 PARAMETER HW_INSTANCE = microblaze_riscv_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.11
 PARAMETER HW_INSTANCE = axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.11
 PARAMETER HW_INSTANCE = microblaze_riscv_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.11
 PARAMETER HW_INSTANCE = microblaze_riscv_0_local_memory_ilmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = simpleSum
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = simpleSum_0
END


